package darksky.modelo.bean;
// Generated 13-feb-2016 16:07:43 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import darksky.exceptions.ExceptionBEAN;
import darksky.util.MyUtil;

/**
 * CategoriaPost generated by hbm2java
 */
@Entity
@Table(name = "categoria_post", catalog = "dark_sky")
public class CategoriaPost implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String categoria;
	private Set<Post> posts = new HashSet<Post>(0);

	public CategoriaPost() {
	}

	public CategoriaPost(String categoria) {
		this.setCategoria(categoria);
	}

	public CategoriaPost(String categoria, Set<Post> posts) {
		this.categoria = categoria;
		this.posts = posts;
	}

	@Id

	@Column(name = "CATEGORIA", unique = true, nullable = false, length = 15)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		if (MyUtil.isEmpty(categoria)) {
			throw new ExceptionBEAN("Categoria no puede ser nula");
		} else if (categoria.length() > 15) {
			throw new ExceptionBEAN("Categoria no puede tener mas de 15 caracteres");
		}
		
		this.categoria = categoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaPost")
	public Set<Post> getPosts() {
		return this.posts;
	}

	public void setPosts(Set<Post> posts) {
		this.posts = posts;
	}

}
