package darksky.modelo.bean;
// Generated 22-may-2016 10:06:30 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ConfirmarAccion generated by hbm2java
 */
@Entity
@Table(name = "confirmar_accion", catalog = "dark_sky")
public class ConfirmarAccion implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private ConfirmarAccionId id;
	private OperacionAutorizacion operacionAutorizacion;
	private String pin;
	private String estado;

	public ConfirmarAccion() {
	}

	public ConfirmarAccion(ConfirmarAccionId id, OperacionAutorizacion operacionAutorizacion, String pin, String estado) {
		this.id = id;
		this.operacionAutorizacion = operacionAutorizacion;
		this.pin = pin;
		this.estado = estado;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", nullable = false, length = 30) ), @AttributeOverride(name = "operacion", column = @Column(name = "OPERACION", nullable = false, length = 50) ) })
	public ConfirmarAccionId getId() {
		return this.id;
	}

	public void setId(ConfirmarAccionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPERACION", nullable = false, insertable = false, updatable = false)
	public OperacionAutorizacion getOperacionAutorizacion() {
		return this.operacionAutorizacion;
	}

	public void setOperacionAutorizacion(OperacionAutorizacion operacionAutorizacion) {
		this.operacionAutorizacion = operacionAutorizacion;
	}

	@Column(name = "PIN", nullable = false, length = 20)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "ESTADO", nullable = false, length = 20)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
