package darksky.modelo.bean;
// Generated 15-abr-2016 18:43:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SeguirPostId generated by hbm2java
 */
@Embeddable
public class SeguirPostId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String usuOrigin;
	private int postTarget;

	public SeguirPostId() {
	}

	public SeguirPostId(String usuOrigin, int postTarget) {
		this.usuOrigin = usuOrigin;
		this.postTarget = postTarget;
	}

	@Column(name = "USU_ORIGIN", nullable = false, length = 30)
	public String getUsuOrigin() {
		return this.usuOrigin;
	}

	public void setUsuOrigin(String usuOrigin) {
		this.usuOrigin = usuOrigin;
	}

	@Column(name = "POST_TARGET", nullable = false)
	public int getPostTarget() {
		return this.postTarget;
	}

	public void setPostTarget(int postTarget) {
		this.postTarget = postTarget;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeguirPostId))
			return false;
		SeguirPostId castOther = (SeguirPostId) other;

		return ((this.getUsuOrigin() == castOther.getUsuOrigin()) || (this.getUsuOrigin() != null && castOther.getUsuOrigin() != null && this.getUsuOrigin().equals(castOther.getUsuOrigin()))) && (this.getPostTarget() == castOther.getPostTarget());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsuOrigin() == null ? 0 : this.getUsuOrigin().hashCode());
		result = 37 * result + this.getPostTarget();
		return result;
	}

}
