package darksky.modelo.bean;
// Generated 19-feb-2016 3:19:12 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import darksky.exceptions.ExceptionBEAN;
import darksky.util.MyUtil;

/**
 * VotosPostId generated by hbm2java
 */
@Embeddable
public class VotosPostId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String usuarioNick;
	private int idPost;

	public VotosPostId() {
	}

	public VotosPostId(String usuarioNick, int idPost) {
		setUsuarioNick(usuarioNick);
		this.idPost = idPost;
	}

	@Column(name = "USUARIO_NICK", nullable = false, length = 30)
	public String getUsuarioNick() {
		return this.usuarioNick;
	}

	public void setUsuarioNick(String usuarioNick) {
		if (MyUtil.isEmpty(usuarioNick)) throw new ExceptionBEAN("El nick de usuario no puede ser nulo");
		this.usuarioNick = usuarioNick;
	}

	@Column(name = "ID_POST", nullable = false)
	public int getIdPost() {
		return this.idPost;
	}

	public void setIdPost(int idPost) {
		this.idPost = idPost;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VotosPostId))
			return false;
		VotosPostId castOther = (VotosPostId) other;

		return ((this.getUsuarioNick() == castOther.getUsuarioNick()) || (this.getUsuarioNick() != null && castOther.getUsuarioNick() != null && this.getUsuarioNick().equals(castOther.getUsuarioNick()))) && (this.getIdPost() == castOther.getIdPost());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsuarioNick() == null ? 0 : this.getUsuarioNick().hashCode());
		result = 37 * result + this.getIdPost();
		return result;
	}

}
