package darksky.modelo.bean;
// Generated 11-feb-2016 3:11:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import darksky.exceptions.ExceptionBEAN;
import darksky.util.MyUtil;

/**
 * CategoriaWiki generated by hbm2java
 */
@Entity
@Table(name = "categoria_wiki", catalog = "dark_sky")
public class CategoriaWiki implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String categoria;
	private Set<PostWiki> postWikis = new HashSet<PostWiki>(0);

	public CategoriaWiki() {
	}

	public CategoriaWiki(String categoria) {
		this.setCategoria(categoria);
	}

	public CategoriaWiki(String categoria, Set<PostWiki> postWikis) {
		this.categoria = categoria;
		this.postWikis = postWikis;
	}

	@Id

	@Column(name = "CATEGORIA", unique = true, nullable = false, length = 30)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		if (MyUtil.isEmpty(categoria)) {
			throw new ExceptionBEAN("Categoria no puede ser nula");
		} else if (categoria.length() > 15) {
			throw new ExceptionBEAN("Categoria no puede tener mas de 15 caracteres");
		}
		
		this.categoria = categoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaWiki")
	public Set<PostWiki> getPostWikis() {
		return this.postWikis;
	}

	public void setPostWikis(Set<PostWiki> postWikis) {
		this.postWikis = postWikis;
	}

}
