package darksky.modelo.bean;
// Generated 11-feb-2016 3:11:32 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import darksky.exceptions.ExceptionBEAN;
import darksky.exceptions.ExceptionDAO;
import darksky.util.MyUtil;
import darksky.util.interfaces.Comment;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name = "comentario", catalog = "dark_sky")
public class Comentario implements java.io.Serializable, Comment {
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Post post;
	private Usuario usuario;
	private String texto;
	private Long votos = new Long(0); //Default 0
	private Date fechaCreacion;
	private Set<Respuesta> respuestas = new HashSet<Respuesta>(0);
	
	@Transient
	private int nivel = 0;
	

	public Comentario() {
	}
	
	public Comentario(Post post, Usuario usuario, String texto) {
		this.setPost(post);
		this.setUsuario(usuario);
		this.setTexto(texto);
		this.setFechaCreacion(MyUtil.getCurrentDate());
	}

	public Comentario(Post post, Usuario usuario, String texto, Date fechaCreacion) {
		this.setPost(post);
		this.setUsuario(usuario);
		this.setTexto(texto);
		this.setFechaCreacion(fechaCreacion);
	}

	public Comentario(Post post, Usuario usuario, String texto, Long votos, Date fechaCreacion, Set<Respuesta> respuestas) {
		this.setPost(post);
		this.setUsuario(usuario);
		this.setTexto(texto);
		this.setVotos(votos);
		this.setFechaCreacion(fechaCreacion);
		this.setRespuestas(respuestas);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		if (id == null) {
			throw new ExceptionDAO("ID no puede ser nulo");
		}
		
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_POST", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		if (post == null) {
			throw new ExceptionBEAN("Post no puede ser nulo");
		}
		
		this.post = post;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROPIETARIO", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		if (usuario == null) {
			throw new ExceptionBEAN("Usuario no puede ser nulo");
		}
		
		this.usuario = usuario;
	}

	@Column(name = "TEXTO", nullable = false)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		if (MyUtil.isEmpty(texto)) {
			throw new ExceptionBEAN("Texto no puede ser nulo");
		} else if (texto.length() > 2000) {
			throw new ExceptionBEAN("Texto no puede tener mas de 255 caracteres");
		}
		
		this.texto = texto;
	}

	@Column(name = "VOTOS", precision = 10, scale = 0)
	public Long getVotos() {
		return this.votos;
	}

	public void setVotos(Long votos) {
		if (votos == null) {
			throw new ExceptionBEAN("Votos no puede ser nulo");
		}
		
		this.votos = votos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_CREACION", nullable = true, length = 19)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	public Set<Respuesta> getRespuestas() {
		return this.respuestas;
	}

	public void setRespuestas(Set<Respuesta> respuestas) {
		this.respuestas = respuestas;
	}
	
	@Transient
	public void setNivel(int nivel) {
		this.nivel = nivel;
	}
	
	@Transient
	public int getNivel() {
		return nivel;
	}

}
