package darksky.modelo.bean;
// Generated 22-may-2016 10:06:30 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConfirmarAccionId generated by hbm2java
 */
@Embeddable
public class ConfirmarAccionId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String usuario;
	private String operacion;

	public ConfirmarAccionId() {
	}

	public ConfirmarAccionId(String usuario, String operacion) {
		this.usuario = usuario;
		this.operacion = operacion;
	}

	@Column(name = "USUARIO", nullable = false, length = 30)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "OPERACION", nullable = false, length = 50)
	public String getOperacion() {
		return this.operacion;
	}

	public void setOperacion(String operacion) {
		this.operacion = operacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfirmarAccionId))
			return false;
		ConfirmarAccionId castOther = (ConfirmarAccionId) other;

		return ((this.getUsuario() == castOther.getUsuario()) || (this.getUsuario() != null && castOther.getUsuario() != null && this.getUsuario().equals(castOther.getUsuario()))) && ((this.getOperacion() == castOther.getOperacion()) || (this.getOperacion() != null && castOther.getOperacion() != null && this.getOperacion().equals(castOther.getOperacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37 * result + (getOperacion() == null ? 0 : this.getOperacion().hashCode());
		return result;
	}

}
