package darksky.modelo.bean;
// Generated 22-may-2016 10:06:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OperacionAutorizacion generated by hbm2java
 */
@Entity
@Table(name = "operacion_autorizacion", catalog = "dark_sky")
public class OperacionAutorizacion implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String operacion;
	private Set<ConfirmarAccion> confirmarAccions = new HashSet<ConfirmarAccion>(0);

	public OperacionAutorizacion() {
	}

	public OperacionAutorizacion(String operacion) {
		this.operacion = operacion;
	}

	public OperacionAutorizacion(String operacion, Set<ConfirmarAccion> confirmarAccions) {
		this.operacion = operacion;
		this.confirmarAccions = confirmarAccions;
	}

	@Id

	@Column(name = "OPERACION", unique = true, nullable = false, length = 50)
	public String getOperacion() {
		return this.operacion;
	}

	public void setOperacion(String operacion) {
		this.operacion = operacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operacionAutorizacion")
	public Set<ConfirmarAccion> getConfirmarAccions() {
		return this.confirmarAccions;
	}

	public void setConfirmarAccions(Set<ConfirmarAccion> confirmarAccions) {
		this.confirmarAccions = confirmarAccions;
	}

}
