package darksky.modelo.bean;
// Generated 11-feb-2016 3:11:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import darksky.exceptions.ExceptionDAO;
import darksky.util.MyUtil;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "dark_sky")
public class Rol implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String rol;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Rol() {
	}

	public Rol(String rol) {
		this.setRol(rol);
	}

	public Rol(String rol, Set<Usuario> usuarios) {
		this.rol = rol;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "ROL", unique = true, nullable = false, length = 15)
	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		if (MyUtil.isEmpty(rol)) {
			throw new ExceptionDAO("Rol no puede ser nulo");
		} else if (rol.length() > 15) {
			throw new ExceptionDAO("Rol no puede tener mas de 15 caracteres");
		}
		this.rol = rol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
